### ISSUE TITLE
"Copy HTML" button broken in Safari

### ISSUE THREAD

**Issue by catleeball** [nex3/cohost-highlight#1]
Hi!

Not sure if you care about browser compat bugs for this, but figured I'd report it just in case.

In Safari browser, clicking the "Copy HTML" button doesn't copy to the clipboard, and doesn't show the butterbar with "copy successful" at the bottom.

Each time the button is clicked, it produces the error `Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.` in the browser console.

Tested in Safari v16.2. Please let me know if you need any more info!

**Comment by ticky** [comment]
Weirdly, it seems to break on webkit pseudo-selectors:

```
> element.matches(".mdc-text-field__input:-webkit-calendar-picker-indicator")
< syntaxerror: The string did not match the expected pattern.
```

I guess it might be worth wrapping this in a try/catch?
